apiVersion: apps/v1
kind: Deployment
metadata:
  name: springkubernetesdemo
spec:
  selector:
      matchLabels:
        app: springkubernetesdemo
  replicas: 3
  template:
    metadata:
      labels:
        app: springkubernetesdemo
    spec:
      containers:
        - name: springkubernetesdemo
          image: atmohsin/springkubernetesdemo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090